# App Name
spring.application.name=quantity-measurement-app

# Server
server.port=8080

# ========================
# SQL DATABASE (DEV)
# ========================
spring.datasource.url=jdbc:mysql://quantitymeasurementdb:3306/quantitydb
spring.datasource.username=quantityadmin
spring.datasource.password=quantity@123

# ========================
# JPA / Hibernate
# ========================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# H2 Console
# ========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================
# Logging  [TRACE<DEBUG<INFO(Default)<WARN<ERROR]
# ========================
#logging.level.root=TRACE
#logging.file.name = app.log
logging.level.org.springframework=INFO
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ========================
# Swagger
# ========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
